export const ROUTES = {
  HOME: "/",
  SERVICES: "/services",
  SERVICE_DETAIL: (slug) => `/services/${slug}`,
  DOCTORS: "/doctors",
  DOCTOR_DETAIL: (id) => `/doctors/${id}`,
  APPOINTMENT: "/appointment",
  ABOUT: "/about",
  BLOG: "/blog",
  BLOG_DETAIL: (slug) => `/blog/${slug}`,
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  ADMIN: "/admin",
  ADMIN_APPOINTMENTS: "/admin/appointments",
  ADMIN_DOCTORS: "/admin/doctors",
  ADMIN_PATIENTS: "/admin/patients",
};
